#Hi...This is Rohit Jaiswal. 
In this notebook I have created a mini project of data science called "Iris Classification".

# Importing libraries...............

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [46]:
import seaborn as sns

In [2]:
from sklearn import metrics

In [4]:
from sklearn import svm

In [5]:
from sklearn.tree import DecisionTreeClassifier

In [44]:
from sklearn.model_selection import train_test_split

# Loading the csv file....................

In [12]:
iris=pd.read_csv('iris.csv')

In [53]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [16]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [54]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [56]:
#Species count.....................
iris['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

# Spliting the dataset...........................

In [20]:
train,test=train_test_split(iris,test_size=0.25)

In [21]:
train

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
92,93,5.8,2.6,4.0,1.2,Iris-versicolor
94,95,5.6,2.7,4.2,1.3,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor
6,7,4.6,3.4,1.4,0.3,Iris-setosa
...,...,...,...,...,...,...
22,23,4.6,3.6,1.0,0.2,Iris-setosa
35,36,5.0,3.2,1.2,0.2,Iris-setosa
47,48,4.6,3.2,1.4,0.2,Iris-setosa
78,79,6.0,2.9,4.5,1.5,Iris-versicolor
134,135,6.1,2.6,5.6,1.4,Iris-virginica

In [22]:
test

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
110,111,6.5,3.2,5.1,2.0,Iris-virginica
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
13,14,4.3,3.0,1.1,0.1,Iris-setosa
90,91,5.5,2.6,4.4,1.2,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
135,136,7.7,3.0,6.1,2.3,Iris-virginica
99,100,5.7,2.8,4.1,1.3,Iris-versicolor
19,20,5.1,3.8,1.5,0.3,Iris-setosa
106,107,4.9,2.5,4.5,1.7,Iris-virginica
26,27,5.0,3.4,1.6,0.4,Iris-setosa
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
11,12,4.8,3.4,1.6,0.2,Iris-setosa
129,130,7.2,3.0,5.8,1.6,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
14,15,5.8,4.0,1.2,0.2,Iris-setosa
114,115,5.8,2.8,5.1,2.4,Iris-virginica
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
140,141,6.7,3.1,5.6,2.4,Iris-virginica
37,38,4.9,3.1,1.5,0.1,Iris-setosa
113,114,5.7,2.5,5.0,2.0,Iris-virginica
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
66,67,5.6,3.0,4.5,1.5,Iris-versicolor
105,106,7.6,3.0,6.6,2.1,Iris-virginica
34,35,4.9,3.1,1.5,0.1,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
118,119,7.7,2.6,6.9,2.3,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
124,125,6.7,3.3,5.7,2.1,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica

In [26]:
train_x=train[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]

In [27]:
train_y=train.Species

In [28]:
train_x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
92             5.8           2.6            4.0           1.2
94             5.6           2.7            4.2           1.3
85             6.0           3.4            4.5           1.6
93             5.0           2.3            3.3           1.0
6              4.6           3.4            1.4           0.3
..             ...           ...            ...           ...
22             4.6           3.6            1.0           0.2
35             5.0           3.2            1.2           0.2
47             4.6           3.2            1.4           0.2
78             6.0           2.9            4.5           1.5
134            6.1           2.6            5.6           1.4

[112 rows x 4 columns]

In [29]:
train_y

92     Iris-versicolor
94     Iris-versicolor
85     Iris-versicolor
93     Iris-versicolor
6          Iris-setosa
            ...
22         Iris-setosa
35         Iris-setosa
47         Iris-setosa
78     Iris-versicolor
134     Iris-virginica
Name: Species, Length: 112, dtype: object

In [47]:
test_x=test[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]

In [31]:
test_y=test.Species

# Training a machine learning model.....................

In [48]:
#SVM
model=svm.SVC()

In [39]:
model.fit(train_x,train_y)
pred=model.predict(test_x)

In [63]:
pred

array(['Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype=object)

In [65]:
model.predict([[1.0,2.0,3.0,8.0]])

C:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Iris-virginica'], dtype=object)

In [70]:
metrics.accuracy_score(pred,test_y)

0.8947368421052632

In [51]:
#DecisionTree
model=DecisionTreeClassifier()

In [52]:
model.fit(train_x,train_y)
pred=model.predict(test_x)

In [67]:
model.predict([[5.1,3.5,1.4,0.2]])

C:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array(['Iris-setosa'], dtype=object)

In [71]:
metrics.accuracy_score(pred,test_y)

0.8947368421052632